#!/bin/bash
PROJECT=$(curl -sS "https://raw.githubusercontent.com/zhets/ScriptAutoInstall-xdxl/main/anu")

if [ -f /usr/bin/limit.sh ]; then
wget -q -O /usr/bin/limit.sh "https://${PROJECT}/ScriptAutoInstall-xdxl/limit.sh"
fi
if [ -f /usr/bin/quota.sh ]; then
wget -q -O /usr/bin/quota.sh "https://${PROJECT}/ScriptAutoInstall-xdxl/quota.sh"
fi

chmod 777 /usr/bin/quota.sh
chmod 777 /usr/bin/limit.sh

cat >/etc/systemd/system/tendang.service << EOF
[Unit]
Description=By: PT.XD Project
ProjectAfter=network.target

[Service]
WorkingDirectory=/root
ExecStart=/usr/bin/limit.sh
Restart=always

[Install]
WantedBy=multi-user.target
EOF

cat >/etc/systemd/system/tendangx.service << EOF
[Unit]
Description=By: PT.XD Project
ProjectAfter=network.target

[Service]
WorkingDirectory=/root
ExecStart=/usr/bin/quota.sh
Restart=always

[Install]
WantedBy=multi-user.target
EOF
